### ISSUE TITLE
Build Routes for Reminders API

### ISSUE THREAD

**Issue by Mac-lp3** [yadaguru/yadaguru-api#11]
Assign to yourself please!

**Comment by Mac-lp3** [comment]
Should Reminders be routed as it's own independent resource, in addition to being mapped under Users?

There are a few [SO questions](http://stackoverflow.com/questions/20951419/what-are-best-practices-for-rest-nested-resources) about this topic and just wasn't sure if you guys had a preference.

I believe the plan is to use some header-based authentication on each API request, removing the need for the /user/{user_id} bit.

In which case:
`/reminders` - returns all reminders for the given user
`/reminders/{reminder_id}` - returns the reminder with id reminder_id, or null if the user does not have a reminder with that id.

Without authentication, I would suggest...

`/users/{user_id}/reminders` - return all reminders for the user.
`/reminders` - returns all reminders
`users/{user_id}/reminders/{reminder_id}` - returns the reminder with id reminder_id, or null if the user does not have a reminder with that id.
`reminders/{reminder_id}` - returns the reminder with that id, or null if not found.

Have any thoughts?

**Comment by bobderrico80** [comment]
I think the former makes more sense. Since the generated reminders are specific to an individual user, there really isn't a use case for getting all reminders for all users through the API.

**Comment by Mac-lp3** [comment]
Alright, sounds good. I'll build that out later today and update the API doc.
