### ISSUE TITLE
Build Routes for Schools API

### ISSUE THREAD

**Issue by Mac-lp3** [yadaguru/yadaguru-api#12]
Assign to yourself before you begin work (plsplspls)

**Comment by Mac-lp3** [comment]
Looks like this resource is also obscured behind `/users` in the API doc.

I was going to go ahead and remove the `/users/{user_id}` bit from the URL in favor of header based identification (see [issue 11](https://github.com/yadaguru/yadaguru-api/issues/11)).

**Comment by bobderrico80** [comment]
Yes, this can be pulled out from  `/users` since we can get the user from the token.

`/schools/{school_id}` can also be added.

Yes, the `user_id` should be stored in the schools object. The table definition for `schools` looks like this:
```
  id        SERIAL PRIMARY KEY             NOT NULL
  userId    INT    REFERENCES Users (id)   NOT NULL
  name      TEXT                           NOT NULL
  dueDate   DATE                           NOT NULL
  isActive  BOOLEAN                        NOT NULL DEFAULT TRUE
```
