### ISSUE TITLE
Build Routes for Users API

### ISSUE THREAD

**Issue by Mac-lp3** [yadaguru/yadaguru-api#13]
Assign to yourself once you start work

**Comment by Mac-lp3** [comment]
Hey guys, I was going to get started on this but noticed something off in the API.

The POST method for `/users` looks like it just returns the ID object, unlike the other POST methods that return the created resource. Just thinking this is pretty non-conventional and didn't know if there was some reason for this service to act this way.

Just let me know and I will get started on it.

**Comment by bobderrico80** [comment]
I believe it should return the whole resource. I think when @adobley initially setup that route, it was more for an example of an overall structure for the controller. Go ahead and return the whole resource.
