### ISSUE TITLE
Agree on method names for resource controllers and services

### ISSUE THREAD

**Issue by bobderrico80** [yadaguru/yadaguru-api#23]
I have noticed some inconsistent naming in the methods on resource controllers and services. We should probably agree on a naming scheme, and keep this consistent.  Here's what I've seen so far:

_Resource Controllers_
**For getting all resources: `get()`, `getAll()`**
**For getting one resource: `getById()`, `getOne()`**
For posting a new resource: `post`
**For putting one resource: `put`, `putOnId`**
For putting multiple resources: `put`
**For deleting a resouce: `del`, `remove`**

_Resource Services_
For finding all: `findAll()`
For finding one by primary key: `findOne(id)`
For finding all by column name: `findByColumnName(value)`
For finding by multiple colums: `findByColumnAandColumnB(valueA, valueB)`
For creating a new resource: `create(data)`
**For updating a resource: `update(data, id)` or `update(resourceWithIdProp)`**
**For deleting a resource: `destroy` or `remove`**
For checking if resource exists: 'exists(id)`

**bold** items are where we have inconsistencies.

**Comment by bobderrico80** [comment]
I'm actually partial to what @Mac-lp3 has been using:

`get()`, `getById()`, `post()`, `put`, `putOnId()`, `remove()` for resource controllers and 

`findAll()`, findByWhatever()`, `create()`, `update()`, `remove()`, and `exists()` for services

...despite it being a little different than I've been doing it.

**Comment by Mac-lp3** [comment]
I'm glad you approve!

For services, I have been using the [Spring Repository naming convention](http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-creation) (I have been a Java/Spring developer most of my career, so I just can't shake the habit).

Basically, the spring framework will parse your method names to generate the query for you, using the syntax I have been writing our methods with. I always thought it was easy to understand what was going on just by reading the method names, so I just kept the convention.

If you guys are okay with using a Java framework's standard, then I would suggest we follow it. It's what I am used to and like I said - it makes it easy to understand what we are looking for without reading the implementation details.

For the controllers, I just tried to extend that naming convention to the HTTP methods. I think coming to an agreement on a naming convention (putON/getBY versus putBY/getON, deleteBY, postON) would be good here.

My thoughts:

**GET**
`get()`

`getBy[Attribute](attribute, [others as needed])` 
`getBySubResourceType[SubAttribute1](subAttribute1, [others as needed])`

`getBy[Attribute1]And[Attribute2](attribute1, attribute2, [others as needed])`
`getBy[Attribute1]AndSubResourceType[Attribute2](attribute1, attribute2, [others as needed])`

`getBy[Attribute1]Or[Attribute2](attribute1, attribute2, [others as needed])`
....

**PUT**
`putOn[Attribute]`
...

** POST**
`postOn[Attribute]`
...

**Delete**
`deleteBy[Attribute]`
...

What do you think?

**Comment by bobderrico80** [comment]
That works for me, as long as we keep it consistent.
